baseURL = "https://gokarna-hugo.netlify.app"
title = "Dario Fadda"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
pygmentsStyle = "monokai"
googleAnalytics = ""

[params]
footer = "Nuke()"
description = "Benvenuti! Qui trovate tutte le mie info, attività e progetti svolti"
avatarURL = "/images/avatar.webp"
AvatarAltText = "avatar"
avatarSize = "size-m"
customHeadHTML = "    <!-- KaTeX -->\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css\" integrity=\"sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC\" crossorigin=\"anonymous\">\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js\" integrity=\"sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja\" crossorigin=\"anonymous\"></script>\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js\" integrity=\"sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR\" crossorigin=\"anonymous\"></script>\n    <script>\n      document.addEventListener(\"DOMContentLoaded\", function() {\n        renderMathInElement(document.body, {\n          // customised options\n          // • auto-render specific keys, e.g.:\n          delimiters: [\n            {left: '$$', right: '$$', display: true},\n            {left: '$', right: '$', display: false},\n          ],\n          // • rendering keys, e.g.:\n          throwOnError : false\n        });\n      });\n    </script>\n  "
metaKeywords = [
  "blog",
  "dariofadda",
  "cybersecurity"
]

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/nuke86"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/dariofadda86/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3BozYFBhM9RXSkFxsTNGowpQ%3D%3D"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/dari_fad/"
  
  [[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/darius.nuke"
  
  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UCP76hO_TFhcPBSTY29oXFNQ"
  
  [[params.socialIcons]]
  name = "mastodon"
  url = "https://mastodon.insicurezzadigitale.com/@nuke"
  
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/nuke86"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:nuke@spcnet.it"

[menu]

  [[menu.main]]
  name = "Home"
  pre = "<span data-feather='home'></span>"
  url = "/"
  weight = 1.0

  [[menu.main]]
  name = "Blog"
  pre = "<span data-feather='book'></span>"
  url = "/posts/"
  weight = 2.0

  [[menu.main]]
  name = "Progetti"
  pre = "<span data-feather='code'></span>"
  url = "/projects/"
  weight = 3.0

  [[menu.main]]
  name = "Tags"
  pre = "<span data-feather='tag'></span>"
  url = "/tags/"
  weight = 4.0

  [[menu.main]]
  identifier = "CV"
  pre = "<span data-feather='resume'></span>"
  url = "/projects/cv"
  weight = 5.0

  [[menu.main]]
  identifier = "rss"
  pre = "<span data-feather='rss'></span>"
  url = "/index.xml"
  weight = 7.0

[markup]

  [markup.tableOfContents]
  startLevel = 1.0
  endLevel = 4.0
  ordered = false
