baseURL = "https://gokarna-hugo.netlify.app"
title = "dariofadda.it"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
pygmentsStyle = "monokai"
googleAnalytics = ""

[params]
footer = "The Marauders"
description = "Sky above, sand below and peace within"
avatarURL = "/images/avatar.webp"
AvatarAltText = "avatar"
avatarSize = "size-m"
customHeadHTML = "    <!-- KaTeX -->\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css\" integrity=\"sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC\" crossorigin=\"anonymous\">\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js\" integrity=\"sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja\" crossorigin=\"anonymous\"></script>\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js\" integrity=\"sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR\" crossorigin=\"anonymous\"></script>\n    <script>\n      document.addEventListener(\"DOMContentLoaded\", function() {\n        renderMathInElement(document.body, {\n          // customised options\n          // • auto-render specific keys, e.g.:\n          delimiters: [\n            {left: '$$', right: '$$', display: true},\n            {left: '$', right: '$', display: false},\n          ],\n          // • rendering keys, e.g.:\n          throwOnError : false\n        });\n      });\n    </script>\n  "
metaKeywords = [
  "blog",
  "gokarna",
  "hugo"
]

  [[params.socialIcons]]
  name = "twitter"
  url = "https://example.com"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://example.com"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://example.com"

  [[params.socialIcons]]
  name = "dribbble"
  url = "https://example.com"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://example.com"

  [[params.socialIcons]]
  name = "twitch"
  url = "https://example.com"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:example@example.com"

[menu]

  [[menu.main]]
  name = "Home"
  pre = "<span data-feather='home'></span>"
  url = "/"
  weight = 1.0

  [[menu.main]]
  name = "Posts"
  pre = "<span data-feather='book'></span>"
  url = "/posts/"
  weight = 2.0

  [[menu.main]]
  name = "Projects"
  pre = "<span data-feather='code'></span>"
  url = "/projects/"
  weight = 3.0

  [[menu.main]]
  name = "Tags"
  pre = "<span data-feather='tag'></span>"
  url = "/tags/"
  weight = 4.0

  [[menu.main]]
  identifier = "github"
  pre = "<span data-feather='github'></span>"
  url = "https://github.com/526avijitgupta/gokarna"
  weight = 5.0

  [[menu.main]]
  identifier = "buymeacoffee"
  pre = "<span data-feather='coffee'></span>"
  url = "https://www.buymeacoffee.com/avijitgupta"
  weight = 6.0

  [[menu.main]]
  identifier = "rss"
  pre = "<span data-feather='rss'></span>"
  url = "/index.xml"
  weight = 7.0

[markup]

  [markup.tableOfContents]
  startLevel = 1.0
  endLevel = 4.0
  ordered = false