hugover = "0.69.0"

[[serve]]
key = "default"
config = "config.toml"

[[build]]
key = "default"
config = "config.toml"

[[collections]]
key = "posts"
title = "Posts"
folder = "content/posts/"
extension = "md"
dataformat = "toml"
itemtitle = "Post"
fields = []

[[collections]]
key = "projects"
title = "Projects"
itemtitle = "Projects"
folder = "content/projects"
extension = "md"
dataformat = "toml"
fields = []

[[singles]]
key = "mainConfig"
title = "Main Config"
file = "config.toml"
dataformat = "toml"

  [[singles.fields]]
  key = "title"
  title = "Site Title"
  type = "string"
  tip = "Your page title."
  required = false
  pattern = ""
  multiLine = false
  default = ""

  [[singles.fields]]
  key = "baseURL"
  title = "Base URL"
  type = "string"
  tip = "Your site URL."
  required = false
  pattern = ""
  multiLine = false
  default = ""

  [[singles.fields]]
  key = "theme"
  title = "Theme"
  type = "readonly"
  tip = "The current theme."
  required = false
  value = ""
  default = ""
  multiLine = false

  [[singles.fields]]
  key = "languageCode"
  title = "Language Code"
  type = "readonly"
  required = false
  value = ""
  default = ""
  multiLine = false
  tip = ""

  [[singles.fields]]
  key = "googleAnalytics"
  title = "Google Analytics"
  type = "string"
  tip = "Provide a Google Analitics Tracking Code to enable analytics."
  required = false
  pattern = ""
  multiLine = false
  default = ""

  [[singles.fields]]
  key = "enableRobotsTXT"
  title = "Enable Robots"
  type = "boolean"
  default = true
  tip = "If you want your page to be indexed, keep this enabled."